url: https://www.contribe.se

# Site settings
title: Contribe
email: brian.ranney@contribe.se
description: "Contribe - Vi förenklar framtiden"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3397b9
  secondary: c39
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Roger Gordin
  pic: roger
  position: VD, Regionchef Skåne
  social:
    - title: linkedin
      url: https://www.linkedin.com/pub/roger-gordin/2/a21/a83
    - title: envelope-o
      url: mailto:roger.gordin@contribe.se

- name: Marcus Nilsson
  pic: marcus
  position: Regionchef Småland
  social:
    - title: linkedin
      url: https://se.linkedin.com/pub/marcus-nilsson/61/70b/561
    - title: envelope-o
      url: mailto:marcus.nilsson@contribe.se

- name: Carin Håkansson
  pic: carin
  position: Regionchef Blekinge
  social:
    - title: linkedin
      url: https://se.linkedin.com/pub/carin-h%C3%A5kansson/9/b35/353
    - title: envelope-o
      url: mailto:carin.hakansson@contribe.se

# Social networks
social:
  - title: facebook
    url: https://www.facebook.com/contribe
  - title: linkedin
    url: https://www.linkedin.com/company/contribe-ab

# Build settings
markdown: kramdown
permalink: pretty

# Customer logos
logos: 
  - url1: kalmar.png
    url2: kalmarColor.png
    alt: kalmar logo
  - url1: volvo.png
    url2: volvoColor.png
    alt: volvo logo
  - url1: playngo.png
    url2: playngoColor.png
    alt: play n go logo
  - url1: hm.png
    url2: hmColor.png
    alt: h and m logo
  - url1: telenor.png
    url2: telenorColor.png
    alt: telenor logo
  - url1: fortnox.png
    url2: fortnoxColor.png
    alt: fortnox logo
  - url1: electra.png
    url2: electraColor.png
    alt: electra logo
  - url1: ericsson.png
    url2: ericssonColor.png
    alt: ericsson logo
  - url1: idata.png
    url2: idataColor.png
    alt: idata logo
  - url1: albinsson.png
    url2: albinssonColor.png
    alt: albinsson and sjöberg logo
  - url1: forsakring.png
    url2: forsakringColor.png
    alt: försakringskassa logo
  - url1: xylem.png
    url2: xylemColor.png
    alt: xylem logo
  - url1: enfo.png
    url2: enfoColor.png
    alt: zipper enfo logo
  - url1: ac.png
    url2: acColor.png
    alt: Åc Karlskrona logo
  - url1: qlik.png
    url2: qlikColor.png
    alt: qlikview logo
  - url1: sandvik.png
    url2: sandvikColor.png
    alt: sandvik logo

#Prose config
prose:
  rooturl: '_posts'
  siteurl: 'http://www.contribe.se'
  media: 'media'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - /_plugins
    - /_site
    - /css
    - /img
    - /js
    - .gitattributes
    - .gitignore
    - CNAME
    - feed.xml
    - index.html
    - LICENSE
    - README.md 
    - style.css
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          value: "default"
      - name: "category"
        field:
          element: "text"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          element: "text"
          value: "true"
      - name: modal-id
        field:
          element: "text"
          value: "enter blog post number here"
